# syntax=docker/dockerfile:1.3
FROM python:3.9-slim

# 1) Install needed system packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends git ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 2) Install Python libraries (including Sentence Transformers, Torch, Qdrant, etc.)
RUN --mount=type=cache,target=/root/.cache/pip \
  pip3 --trusted-host download.pytorch.org \
  install \
  javalang \
  torch \
  pyesprima \
  sentence-transformers \
  qdrant-client \
  gitpython \
  --extra-index-url http://download.pytorch.org/whl/cpu


# 3) **Pre-download the model** from Hugging Face and store it in /app/model
#    This command fetches "sentence-transformers/all-MiniLM-L6-v2" at build time.

#COPY app/models/all-MiniLM-L6-v2 app/models/all-MiniLM-L6-v2

# 5) Copy your index script
COPY static_prompts_indexer_script.py .

# 6) At runtime, run index_script.py, which now can load from /app/model
ENTRYPOINT ["python3", "static_prompts_indexer_script.py"]
