services:
  rag-architect:
    platform: linux/amd64
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=generic
      - GENERIC_SERVER_URL=https://bedrock.devaws.company.com/bedrock/converse
      - VLLM_SERVER_URL=http://vllm:8082
      - JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - qdrant
      - embedding-service
    profiles:
      - generic

  qdrant:
    profiles:
      - generic

  git-indexer-1:
    profiles:
      - generic

  confluence-indexer-1:
    profiles:
      - generic

  static-prompt-indexer-1:
    profiles:
      - generic

  embedding-service:
    profiles:
      - generic 