FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates


# Preload any models you want here.
# See https://ollama.com/library
RUN nohup ollama serve & \
    for i in $(seq 1 30); do \
        if ollama list >/dev/null 2>&1; then break; fi; \
        echo "Waiting for Ollama to start... ($i/30)"; \
        sleep 2; \
    done

EXPOSE 11411
# Ensure Ollama starts properly
ENTRYPOINT ["ollama"]
CMD ["serve"]